package io.github.unacceptable.alias;

import java.util.HashMap;
import java.util.Map;
import java.util.function.Function;

/**
 * Generates and stores randomly-generated values for alias names. For example, an AliasStore might map username aliases
 * (used in tests) to displayNames (used by the driver).
 */
public class AliasStore<T> {

    private final Map<String, T> valueByAliasMap = new HashMap<>();
    private final Function<String, T> valueGenerator;

    public AliasStore(Function<String, T> valueGenerator) {
        this.valueGenerator = valueGenerator;
    }

    /**
     * Converts an alias into a (possibly generated) value.
     * <p>
     * First, {@code null} alias are mapped to {@code null} and returned as-is.
     * <p>
     * If the alias was not {@code null}, if the alias has never been used before in this AliasStore, a value
     * will be generated by passing the alias to the underlying generator. The result will be stored for
     * future use, then returned.
     * <p>
     * Finally, if the alias <em>has</em> been generated before, the previous result will be returned directly.
     *
     * @param alias
     *         the alias to find a value for, or {@code null}.
     * @return the resulting value, or {@code null} if the alias was {@code null}.
     */
    public T resolve(String alias) {
        if (alias == null) {
            return null;
        }
        // computeIfAbsent handles null in ways that are incompatible with #store(...) below.
        if (valueByAliasMap.containsKey(alias)) {
            return valueByAliasMap.get(alias);
        }

        T value = valueGenerator.apply(alias);
        valueByAliasMap.put(alias, value);
        return value;
    }

    /**
     * Set an alias to a specific, known value. This value will be returned from future calls to {@link
     * #resolve(String)}} for the same alias.
     *
     * @param alias
     *         the alias to store.
     * @param value
     *         the value to store for the alias. This may be {@code null}; resolving the alias in this case will return
     *         {@code null}.
     */
    public void store(String alias, T value) {
        valueByAliasMap.put(alias, value);
    }
}
