#!/usr/bin/env python3

import sys
import sedump.gamedata as sg
import sedump.templates as st
import sedump.output as so

def main():
    gamedata = sg.GameData.from_directory('Data')
    output = so.Output('wiki')
    environment = st.environment(gamedata)

    with output.open('Home.md', 'w', encoding='UTF-8') as f:
        template = environment.get_template('Home.md')
        stream = template.stream()
        stream.dump(f)

    for component in gamedata.components:
        filename = r'Component-{0.id.subtype_id}.md'.format(component)
        with output.open(filename, 'w', encoding='UTF-8') as f:
            template = environment.select_template([filename, 'Component-default.md'])
            stream = template.stream(component=component)
            stream.dump(f)

    for block in gamedata.blocks:
        filename = r'Block-{0.id.type_id}-{0.id.subtype_id}.md'.format(block)
        with output.open(filename, 'w', encoding='UTF-8') as f:
            template = environment.select_template([filename, 'Block-default.md'])
            stream = template.stream(block=block)
            stream.dump(f)

if __name__ == '__main__':
    sys.exit(main())
