#!/bin/bash -e

cd "$(dirname "$0")"
BIN="${PWD}"
cd -

SOURCE_REPO="$1"
TARGET_REPO="$2"
shift 2

while [ $# -gt 0 ]; do
	DIR="$1"
	shift

	EPHEMERAL_REPO="$(mktemp -d -t git-transplant)"

	cd "${SOURCE_REPO}"
	"${BIN}/git-export-dir" "${EPHEMERAL_REPO}" "${DIR}"
	cd -

	cd "${TARGET_REPO}"
	"${BIN}/git-attach-history" "${EPHEMERAL_REPO}" -m "Transplant history of ${DIR} from ${SOURCE_REPO}"
	cd -

	rm -rf "${EPHEMERAL_REPO}"
done