#!/usr/bin/env python

from time import sleep
from hacksign import Frame
from hacksign.driver import loop

host = "192.168.111.4"
port = 2330

def random_pixel (height = 32, width = 96):
    from random import seed, randint
    return (randint (0, width - 1), randint (0, height - 1))

def frame_function ():
    sleep (0.1)
    image = Frame ()

    for i in range (0, 64):
        x, y = random_pixel ()
        image.set_pixel (x, y)

    return image

loop (host, port, frame_function)
