#!/usr/bin/env python

from time import sleep
from hacksign import Frame
from hacksign.driver import loop

host = "192.168.111.4"
port = 2324
image = "steev.txt"

file = open (image, 'r')
lines = file.readlines ()
file.close ()

# kill whitespace
lines = [line.strip () for line in lines]
rasters = [map (int, line) for line in lines]

image = Frame ()

for row in range (0, len (rasters)):
    raster = rasters[row]
    for col in range (0, len (raster)):
        image.set_pixel (col, row, raster[col])

loop (host, port, lambda : image)
