package io.github.unacceptable.alias;

import java.util.Random;

public class UsernameGenerator {
    private static final Random RANDOM = new Random();
    private static final int MAX_LENGTH = 32;
    private static final String SEPARATOR = "-";

    private UsernameGenerator() {
        throw new UnsupportedOperationException();
    }

    /**
     * Generates random usernames, given a username template. A random suffix, generated by selecting a random
     * non-negative <code>long</code> and formatting it as lowercase hexadecimal, will be appended to the name. The
     * resulting name will be no longer than {@value #MAX_LENGTH} characters or the length of the original alias,
     * whichever is longer.
     * <p>
     * This method is suitable for use in an {@link AliasStore}.
     *
     * @param alias
     *         a username alias, such as <code>"derek"</code>.
     * @return a randomly-generated username, such as <code>"derek-abad1dea"</code>.
     */
    public static String generate(String alias) {
        String unique = generateUniquePart();
        return concat(alias, unique);
    }

    private static String concat(String alias, String unique) {
        int maxLengthOfAliasToUse = MAX_LENGTH - SEPARATOR.length()
                - unique.length();
        if (maxLengthOfAliasToUse > alias.length()) {
            return alias + SEPARATOR + unique;
        } else if (maxLengthOfAliasToUse > 0) {
            return alias.substring(0, maxLengthOfAliasToUse) + SEPARATOR
                    + unique;
        } else {
            return unique;
        }
    }

    private static String generateUniquePart() {
        long nonce = RANDOM.nextLong();
        return String.format("%016x", nonce);
    }
}
